# Generated by Django 2.2.16 on 2022-03-29 20:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя категории', max_length=256, verbose_name='Имя категории')),
                ('slug', models.SlugField(help_text='Введите уникальный идентификатор категории', unique=True, verbose_name='Уникальный идентификатор категории')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименоване жанра', max_length=256, verbose_name='Наименование жанра')),
                ('slug', models.SlugField(help_text='Введите уникальный идентификатор жанра', unique=True, verbose_name='Уникальный идентификатор жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название произведения')),
                ('year', models.IntegerField(help_text='Введите год создания произведения', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4999)], verbose_name='Год создания')),
                ('description', models.TextField(help_text='Введите описание произведения', verbose_name='Описание')),
                ('category', models.ForeignKey(help_text='Введите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='yamdb.Category', verbose_name='Категория')),
                ('genre', models.ForeignKey(help_text='Выберите жанр', on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='yamdb.Genre', verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Revew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст отзыва', verbose_name='Текст отзыва')),
                ('score', models.IntegerField(help_text='Укажите вашу оценку произведения', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Укажите дату отзыва', verbose_name='Дата отзыва')),
                ('author', models.ForeignKey(help_text='Укажите автора', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('title', models.ForeignKey(help_text='Выберите произведение', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='yamdb.Title', verbose_name='review')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Введите дату отзыва', verbose_name='Дата отзыва')),
                ('text', models.TextField(help_text='Введите текст отзыва', verbose_name='Текст отзыва')),
                ('author', models.ForeignKey(help_text='Укажите автора', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('review', models.ForeignKey(help_text='Укажите отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='yamdb.Revew', verbose_name='Отзыв')),
                ('title', models.ForeignKey(help_text='Укажите произведение', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='yamdb.Title', verbose_name='Произведение')),
            ],
        ),
    ]
