# Generated by Django 2.2.16 on 2022-04-03 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(help_text='Введите год создания произведения', validators=[django.core.validators.MaxValueValidator(2022)], verbose_name='Год создания'),
        ),
    ]
