# Generated by Django 2.2.16 on 2022-03-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='title',
            name='unique_title',
        ),
    ]
