# Generated by Django 2.2.16 on 2022-03-30 18:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yamdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Revew',
            new_name='Review',
        ),
    ]
