# Generated by Django 2.2.16 on 2022-04-01 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yamdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Revew',
            new_name='Review',
        ),
        migrations.RemoveField(
            model_name='title',
            name='category',
        ),
        migrations.AddField(
            model_name='title',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Категория', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='yamdb.Category'),
        ),
    ]
