# Generated by Django 2.2.16 on 2022-03-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0003_auto_20220331_0524'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='title',
            name='unique_categorytitle',
        ),
        migrations.AddConstraint(
            model_name='title',
            constraint=models.UniqueConstraint(fields=('name', 'year'), name='unique_title'),
        ),
    ]
